### ISSUE TITLE
Not working in FF Developer edition

### ISSUE THREAD

**Issue by SleepProgger** [diracdeltas/sniffly#1] opened 2015-10-26 07:52 UTC
Just a little heads up:
I played a bit with the project and noticed it is working in the current FF release (not as nicely as in chrome but it works with adding the CSP header via PHP), but didn't work in the FF Developer edition.

In fact it looks like dev edition ignores the CSP rule completely as it happily displays images from an HTTPS source.

**Comment by diracdeltas** [comment] 2015-10-26 16:53
In the developer tools console, do you see the CSP rule being sent correctly? If so, that sounds like a FF bug. 

Could you try changing the CSP syntax to `img-src http:`?

**Comment by jomo** [comment] 2015-10-26 19:38
From `security csp` in the Developer Toolbar, it also shows up like that in response headers:
![CSP screenshot](https://i.imgur.com/xdoQYch.png)

---

> it happily displays images from an HTTPS source

Can confirm, was able to append that HTTPS screenshot to the page:

![https screenshot](https://i.imgur.com/T9oykqt.png)

---

To be fair, it doesn't seem to make a lot of sense to restrict images to insecure URLs, but I would agree that's a bug.

**Comment by diracdeltas** [comment] 2015-10-26 19:42
I also confirmed this, and it's definitely a bug according to the CSP spec. Testing it out in csptester.io, it looks like Firefox Dev Edition does _not_ ignore 'img-src https:' but does ignore 'img-src http:'.

**Comment by diracdeltas** [comment] 2015-10-26 19:59
Filed https://bugzilla.mozilla.org/show_bug.cgi?id=1218524

**Comment by diracdeltas** [comment] 2015-10-28 08:09
Also see https://github.com/w3c/webappsec-csp/issues/25

**Comment by diracdeltas** [comment] 2015-12-22 08:22
Update: FF and Chrome have decided that ignoring the http-only CSP directive is correct. As a workaround, Sniffly Firefox uses crbug 436451 for sniffing. Closing for now; please reopen if it still doesn't work!

**Closed as completed by diracdeltas** 2015-12-22 08:22 UTC
